AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Complete order processing system

Resources:
  # API Gateway for Order Submission
  OrderApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: OrderAPI
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"
  
  # Lambda for being triggered by apigw 
  ApiGatewayHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api_gateway_handler.lambda_handler
      Runtime: python3.9
      CodeUri: ./src
      MemorySize: 128
      Timeout: 15
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref OrderEventBus
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - "events:PutEvents"
            Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${OrderEventBus}"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref OrderApiGateway
            Path: /order
            Method: POST

  # EventBridge for Coordination
  OrderEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: OrderEventBus

  # DynamoDB Table for Order Status
  OrderStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: OrderStatus
      AttributeDefinitions:
        - AttributeName: OrderId
          AttributeType: S
      KeySchema:
        - AttributeName: OrderId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # SQS Queues for Decoupling
  ValidOrderQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ValidOrderQueue

  OrderValidationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OrderValidationDLQ

  # OrderProcessorDLQ:
  #   Type: AWS::SQS::Queue
  #   Properties:
  #     QueueName: OrderProcessorDLQ

  # Lambda: Order Validation
  OrderValidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: order_validation.lambda_handler
      Runtime: python3.9
      CodeUri: ./src
      MemorySize: 128
      Timeout: 15
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref OrderEventBus
          VALID_ORDER_QUEUE: !Ref ValidOrderQueue
          INVALID_ORDER_DLQ: !Ref OrderValidationDLQ
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - "events:PutEvents"
            Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${OrderEventBus}"
        - Statement:
            Effect: Allow
            Action:
              - "sqs:SendMessage"
            Resource: !GetAtt ValidOrderQueue.Arn
        - Statement:
            Effect: Allow
            Action:
              - "sqs:SendMessage"
            Resource: !GetAtt OrderValidationDLQ.Arn
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt OrderValidationDLQ.Arn
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "com.ordersystem.order"
              detail-type:
                - "OrderCreated"
            EventBusName: !Ref OrderEventBus

  # Lambda: Inventory Processor
  InventoryProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: inventory_handler.lambda_handler
      Runtime: python3.9
      CodeUri: ./src
      MemorySize: 128
      Timeout: 15
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref OrderStatusTable
          EVENT_BUS_NAME: !Ref OrderEventBus
          # INVALID_ORDER_PROCESSOR_DLQ: !Ref OrderProcessorDLQ
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrderStatusTable
        - Statement:
            Effect: Allow
            Action:
              - "events:PutEvents"
            Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${OrderEventBus}"
        - Statement:
            Effect: Allow
            Action:
              - "sqs:ReceiveMessage"
              - "sqs:GetQueueAttributes"
            Resource: !GetAtt ValidOrderQueue.Arn
      #   - Statement:
      #       Effect: Allow
      #       Action:
      #         - "sqs:SendMessage"
      #       Resource: !GetAtt OrderProcessorDLQ.Arn
      # DeadLetterQueue:
      #   Type: SQS
      #   TargetArn: !GetAtt OrderProcessorDLQ.Arn
      Events:
        SQSQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt ValidOrderQueue.Arn
            BatchSize: 1

  # Lambda: Order Completion
  OrderCompletionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: completion_handler.lambda_handler
      Runtime: python3.9
      CodeUri: ./src
      MemorySize: 128
      Timeout: 15
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref OrderStatusTable
          EVENT_BUS_NAME: !Ref OrderEventBus
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrderStatusTable
        - Statement:
            Effect: Allow
            Action:
              - "events:PutEvents"
            Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${OrderEventBus}"
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "com.ordersystem.order"
              detail-type:
                - "InventorySuccess"
            EventBusName: !Ref OrderEventBus

  # Lambda: Notification
  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: notification_handler.lambda_handler
      Runtime: python3.9
      CodeUri: ./src
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref OrderNotificationTopic
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - "sns:Publish"
            Resource: !Ref OrderNotificationTopic
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "com.ordersystem.order"
              detail-type:
                - "OrderCompleted"
            EventBusName: !Ref OrderEventBus

  # SNS Topic for Notifications
  OrderNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: OrderNotificationTopic

Outputs:
  OrderApiUrl:
    Value: !Sub "https://${OrderApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/order"
    Description: URL for the Order API