name: Deploy SAM Stack

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      aws-region:
        description: 'The AWS region'
        required: true
        default: 'us-east-1'
jobs:
  deploy:
    name: Deploy SAM Stack to AWS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}

    - name: Install SAM CLI
      run: |
        if ! sam --version; then
          curl -LO "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip"
          unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
          sudo ./sam-installation/install
        else
          echo "SAM CLI is already installed with current version:"
          sam --version
        fi

    - name: Build SAM Application
      run: sam build

    - name: Deploy SAM Stack
      run: |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name OrderProcessingStack \
          --capabilities CAPABILITY_NAMED_IAM \
          --region ${{ inputs.aws-region }}
